In [ ]:
#data preprocessing: handling NA values
#Linear multivarite regression
import pandas as pd
import numpy as np
from sklearn import linear_model
df = pd.read_csv("homeprice01.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [ ]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

AttributeError: 'DataFrame' object has no attribute 'bedrooms'

In [ ]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']],df.price)

LinearRegression()

In [ ]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [ ]:
reg.intercept_

np.float64(383724.9999999998)

In [ ]:
reg.predict([[2500,4,5]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])

In [ ]:
#Salary prediction (2 sum )

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model
df = pd.read_csv("Salary prediction.csv")
df

Employe Experience  test_score(out of 10)  interview_score(out of 10)  Salary
0                NaN                    8.0                           9   55000
1                NaN                    8.0                           6   45000
2               five                    6.0                           7   60000
3                two                   10.0                          10   65000
4              seven                    9.0                           6   70000
5              three                    7.0                          10   62000
6                ten                    NaN                           7   72000
7             eleven                    7.0                           8   80000

In [ ]:
import math
median_test_score_value = math.floor(df['test_score(out of 10)'].median())
median_test_score_value

8

In [ ]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_test_score_value)
df

Employe Experience  test_score(out of 10)  interview_score(out of 10)  Salary
0             eleven                    8.0                           9   55000
1             eleven                    8.0                           6   45000
2               five                    6.0                           7   60000
3                two                   10.0                          10   65000
4              seven                    9.0                           6   70000
5              three                    7.0                          10   62000
6                ten                    8.0                           7   72000
7             eleven                    7.0                           8   80000

In [ ]:
df['Employe Experience'] = df['Employe Experience'].fillna("zero")
df

Employe Experience  test_score(out of 10)  interview_score(out of 10)  Salary
0             eleven                    8.0                           9   55000
1             eleven                    8.0                           6   45000
2               five                    6.0                           7   60000
3                two                   10.0                          10   65000
4              seven                    9.0                           6   70000
5              three                    7.0                          10   62000
6                ten                    8.0                           7   72000
7             eleven                    7.0                           8   80000

In [ ]:
from word2number import w2n
df['Employe Experience'] = df['Employe Experience'].apply(w2n.word_to_num)
df

Employe Experience  ...  Salary
0                  11  ...   55000
1                  11  ...   45000
2                   5  ...   60000
3                   2  ...   65000
4                   7  ...   70000
5                   3  ...   62000
6                  10  ...   72000
7                  11  ...   80000

[8 rows x 4 columns]

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df[['Employe Experience','test_score(out of 10)','interview_score(out of 10)']],df.Salary)

LinearRegression()

In [ ]:
reg.coef_

array([ 18.55778062,  58.95228367, 579.17957786])

In [ ]:
reg.intercept_

np.float64(58460.52823580914)

In [ ]:
18.55778062*11+58.95228367*7+579.17957786*8+58460.52823580914

63710.76643119914

In [ ]:
reg.predict([[11,7.0,8]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([63710.76643119])